spring.application.name=rent_db

# DBConnect
spring.datasource.url = jdbc:mysql://localhost:3306/rent_db?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = Laksme@28

#Hibernate Settings
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl_auto =update
